import pyBrainAnalyzIR.media.spectra
import pyBrainAnalyzIR.media.optical_properties
import pyBrainAnalyzIR.media.tissues
from pyBrainAnalyzIR.media.spectra import getspectra
from pyBrainAnalyzIR.media.optical_properties import SpectralProp
